# Generated by Django 5.2.11 on 2026-02-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('category', models.CharField(choices=[('business', 'Бизнес'), ('education', 'Образование'), ('services', 'Услуги')], default='business', max_length=20, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('kpi_line_1', models.CharField(blank=True, max_length=100, verbose_name='KPI строка 1')),
                ('kpi_line_2', models.CharField(blank=True, max_length=100, verbose_name='KPI строка 2')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cases/', verbose_name='Изображение')),
                ('platform', models.CharField(blank=True, max_length=100, verbose_name='Платформа')),
                ('launch_days', models.CharField(blank=True, max_length=50, verbose_name='Срок запуска')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы / Портфолио',
                'ordering': ('order', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='HeroBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_highlight', models.CharField(blank=True, help_text='Например: «а не как визитка»', max_length=100, verbose_name='Выделенная часть заголовка (синим)')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('note', models.CharField(blank=True, help_text='Например: Ответим в течение 15 минут. Без навязывания.', max_length=200, verbose_name='Текст под кнопками')),
                ('is_active', models.BooleanField(default=True, verbose_name='Использовать на сайте')),
            ],
            options={
                'verbose_name': 'Главный экран',
                'verbose_name_plural': 'Главный экран',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('contact', models.CharField(max_length=200, verbose_name='Телефон или Telegram')),
                ('contact_method', models.CharField(choices=[('phone', 'Телефон'), ('telegram', 'Telegram')], default='phone', max_length=20, verbose_name='Способ связи')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('service_type', models.CharField(blank=True, max_length=100, verbose_name='Тип услуги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('lead_text', models.CharField(blank=True, max_length=200, verbose_name='Вводный текст')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('button_text', models.CharField(default='Узнать подробнее', max_length=100, verbose_name='Текст кнопки')),
                ('places_left', models.PositiveSmallIntegerField(blank=True, default=5, null=True, verbose_name='Осталось мест')),
                ('is_active', models.BooleanField(default=True, verbose_name='Акция активна')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Код')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Краткое описание')),
                ('price_from', models.CharField(blank=True, max_length=50, verbose_name='Цена от')),
                ('features', models.TextField(blank=True, help_text='Один пункт на строку', verbose_name='Что входит (каждый пункт с новой строки)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Выделенная карточка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SiteBiz Lab', max_length=100, verbose_name='Название сайта')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('vk', models.URLField(blank=True, verbose_name='VK')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Описание для поисковиков')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
