# Generated by Django 4.2.28 on 2026-03-03 14:12

from django.db import migrations, models
from django.utils.text import slugify


def fill_case_slugs(apps, schema_editor):
    Case = apps.get_model('content', 'Case')
    used = set()
    for case in Case.objects.all():
        base = (slugify(case.title) or 'case')[:100]
        slug = base
        i = 1
        while slug in used:
            slug = f'{base}-{i}'[:120]
            i += 1
        used.add(slug)
        case.slug = slug
        case.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_update_hero_main_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='product_type',
            field=models.CharField(blank=True, choices=[('sites', 'Сайты'), ('bots', 'Telegram-боты'), ('miniapps', 'MiniApps')], default='sites', max_length=20, verbose_name='Продукт (фильтр на главной)'),
        ),
        migrations.AddField(
            model_name='case',
            name='slug',
            field=models.SlugField(blank=True, help_text='Для страницы кейса. Оставьте пустым — подставится из названия.', max_length=120, null=True, unique=False, verbose_name='URL кейса'),
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('business', 'Для бизнеса'), ('education', 'Для образования'), ('services', 'Для услуг'), ('startups', 'Для стартапов')], default='business', max_length=20, verbose_name='Категория'),
        ),
        migrations.RunPython(fill_case_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=models.SlugField(blank=True, help_text='Для страницы кейса. Оставьте пустым — подставится из названия.', max_length=120, unique=True, verbose_name='URL кейса'),
        ),
    ]
