# Generated by Django 4.2.28 on 2026-03-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_add_case_slug_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, help_text='С какой страницы пришла заявка (лендинг, главная, форма в герое и т.д.)', max_length=200, verbose_name='Источник (страница)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='service_type',
            field=models.CharField(blank=True, help_text='На какую услугу или тариф оставили заявку (раздел услуг, выбор на странице Сайты и т.д.)', max_length=200, verbose_name='Услуга / пакет'),
        ),
    ]
